let objInfo = new info();
objInfo.allReady();
let objIdex = new index();
objIdex.allReady();
let objConstants = new constants();
objConstants.allReady();
let objOnArray = new onArray();
objOnArray.allReady();
let objPiece = new piece();
objPiece.allReady();
let objTile = new tile();
objTile.allReady();
let objBoard = new board();
objBoard.allReady();
let objMovements = new movements();
objMovements.allReady();
let objInteligence = new ingeligence();
objInteligence.allReady();